spring:
  application:
    name: social_facebook
    
  datasource:
    url: jdbc:mariadb://localhost:3306/sales
    username: root    
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    
