spring:
  application:
    name: social_facebook
    
  datasource:
    url: jdbc:mariadb://localhost:3306/sales
    username: root    
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    generate-unique-name: false
    name: tacocloud

    
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
